version: "3"
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - app
  atmo:
    build: .
    environment:
      ATMO_HTTP_PORT: "8080"
    ports:
      - "8080:8080"
    networks:
      - app
    volumes:
      - ./:/home/atmo/

networks:
  app: